services:
  postgres:
    image: postgres:16
    container_name: pg-fastapi
    restart: unless-stopped
    environment:
      POSTGRES_USER: hadi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastapi-net

volumes:
  pgdata:

networks:
  fastapi-net:
